config/routes.rb
Rails.application.routes.draw do
  
	root 'welcome#index'
	get "/em_breve", to: "welcome#coming", as: :coming
	get "/about", to: "welcome#about", as: :about
	
	resources :comments
	resources :favorites

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates_presence_of :name, :content
	has_many :favorites
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :comment
	validates_uniqueness_of :address, scope: :comment_id
end

app/controllers/api/api_controller.rb
class API::APIController < ActionController::Base
end

app/controllers/api/comments_controller.rb
class API::CommentsController < API::APIController

	def index
		@count = params[:count]
		@comment_id = params[:comment_id]

		if @count
			@comments = Comment.last(@count).reverse
			render json: @comments, status: :ok
		elsif @comment_id
			@comment = Comment.find(@comment_id)
			render json: @comment.favorites.count, status: :ok
		else
			render json: Comment.all.reverse, status: :ok
		end
		
	end

	def create
		@comment = Comment.new(comment_params)

		if @comment.save
			render json: @comment, status: :ok
		else
			render json: @comment.erros, stauts: :no_conttent
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:name, :content, :address)
	end

end

app/controllers/api/favorites_controller.rb
class API::FavoritesController < API::APIController

	def index
		@comment_id = params[:comment_id]
		if @comment_id
			@comments = Comment.find params[:comment_id]
			render json: @comments, include: :favorites, status: :ok
		else
			@comments = Comment.all
			render json: @comments, include: :favorites, status: :ok
		end
	end

	def create
		@favorite = Favorite.new(favorite_params)
		@favorite.address = request.remote_ip

		if @favorite.save
			render json: @favorite, as: :ok
		else
			render json: @favorite.errors, as: :no_content
		end
	end

	private
	def favorite_params
		params.require(:favorite).permit(:address, :comment_id)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
		@comment = Comment.new
	end

	def create
		@comment = Comment.new(comment_params)
		@comment.address = request.remote_ip

		if verify_recaptcha(model: @comment) && @comment.save
			redirect_to comments_path
		else
			render :index
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:name, :content, :address)
	end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def index
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/create.js.erb
$('.add-comment').bind('ajax:success', function() {  
    $(".message-box").append("
    	<h4>{{comment.name}}</h4>
		<p>{{comment.content}}</p>
		<div ng-controller='FavoriteIndex as rk' ng-init='rk.comment_id = comment.id; rk.ranking();' >
			<button ng-click='rk.addRanking()', class='add-ranking'>
				<span>Inutilidade: {{rk.rankingValue}}</span> +
			</button>
		</div>
	");
}); 

app/views/comments/index.html.erb
<div class="mdl-card mdl-card-wide mdl-shadow--2dp card-new">
	<h4>Comenta ai!</h4>
	<%= form_for @comment do |comment| %>
	<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" style="width: 100%;">
		<%= comment.text_field :name, class: "mdl-textfield__input shadow-inset", placeholder: "Qual o seu nome mesmo?" %>
	</div>
	<div class="mdl-textfield mdl-js-textfield" style="width: 100%;">
		<%= comment.text_area :content, class: "mdl-textfield__input shadow-inset", placeholder: "Manda seu melhor comentário!" %>
	</div>

	<div class="mdl-textfield mdl-js-textfield" style="width: 100%;">
		<%= recaptcha_tags %>
	</div>

	<div class="mdl-card__actions mdl-card--border">
		<%= comment.submit "Comentar", class: "mdl-button mdl-button--raised mdl-button--colored mdl-js-button mdl-js-ripple-effect btn-primary add-comment", remote: :true, method: "post" %>
	</div>
	<% end %>
</div>

<div ng-controller="CommentIndex as vm" ng-init="vm.count = 10; vm.load();">
	<div class="comments">
		<div ng-repeat="comment in vm.comments" class="message-box" ng-class="{'box-right': vm.messagePosition(comment.address)}" >
			<h4>{{comment.name}}
				<p class="points" style="color: red;" ng-controller="FavoriteIndex as rk" ng-init="rk.comment_id = comment.id; rk.ranking();">
					<i class="material-icons add-ranking" ng-click="rk.addRanking()">favorite</i> 
					<span style="position: relative; top: -5px; font-size: 1.5em; margin-left: 5px;">{{rk.rankingValue}}</span>
				</p>
			</h4>
			<p>{{comment.content}}</p>

		</div>
	</div>

	<button class="mdl-button mdl-button--raised btn mdl-js-button mdl-js-ripple-effect btn-welcome" ng-click="vm.count = vm.count + 10; vm.load();" style="width: 100%; top: 0px; margin: 20px 0;">Ver mais inutilidades</button>
</div>

app/views/favorites/index.html.erb
<div ng-controller="FavoriteIndex as rk" ng-init="rk.loadRanking();">
	<div class="comments">
		<div ng-repeat="comment in rk.comments | orderBy : '-favorites' | limitTo: 10" class="message-box" ng-class="{'box-right': rk.messagePosition(comment.address)}" >

			<h4 ng-init="rk.comment_id = comment.id;  rk.ranking();">{{comment.name}}
				<p class="points" style="color: red;">
					<i class="material-icons add-ranking" ng-click="rk.addRanking()">favorite</i> 
					<span style="position: relative; top: -5px; font-size: 1.5em; margin-left: 5px;">{{comment.favorites.length}}</span>
				</p>
			</h4>

			<p>{{comment.content}}</p>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inutil</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  	<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.blue-pink.min.css" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= csrf_meta_tags %>
  </head>

  <body class="mdl-layout mdl-js-layout mdl-layout--fixed-header" ng-app="app">
  	<header class="mdl-layout__header mdl-color--white ">
      <div aria-expanded="false" role="button" tabindex="0" class="mdl-layout__drawer-button mdl-layout--small-screen-only">
        <i class="material-icons"></i>
      </div>
      
  		<div class="mdl-layout__header-row ">
        <i class="material-icons mdl-layout-icon" style="color: #0d9abd;">mode_comment</i>
  			<%= link_to "INUTIL", root_path, class: "mdl-title title-menu mdl-color-text--grey-800" %>

  			<div class="mdl-layout-spacer"></div>

  			<nav class="mdl-navigation mdl-layout--large-screen-only ">
          <%= link_to comments_path, class: "mdl-navigation__link mdl-color-text--grey-800" do %>
            <i class="material-icons mdl-color-text--grey-500 message">message</i> Comentarios
          <% end %>

          <%= link_to favorites_path, class: "mdl-navigation__link mdl-color-text--grey-800" do %>
            <i class="material-icons mdl-color-text--grey-500 favorite">favorite</i> Ranking
          <% end %>

          <%= link_to about_path, class: "mdl-navigation__link mdl-color-text--grey-800" do %>
            <i class="material-icons mdl-color-text--grey-500 about">person_pin</i> Sobre
          <% end %>
  			</nav>
  		</div>
  	</header>

    <div class="mdl-layout__drawer mdl-layout--small-screen-only">
      <i class="button-close-menu material-icons">close</i>
      <span class="mdl-layout-title font-title light-color">
        <%= link_to "INUTIL", root_path, class: "title-menu light-color", style: "margin-left: 0;" %>
      </span>
      <nav class="mdl-navigation small-screen-only">
        <%= link_to comments_path, class: "mdl-navigation__link light-color" do %>
          Comentarios
        <% end %>
        <%= link_to favorites_path, class: "mdl-navigation__link light-color" do %>
          Ranking
        <% end %>
        <%= link_to about_path, class: "mdl-navigation__link light-color" do %>
          Sobre
        <% end %>
      </nav>
    </div>

    <main class="mdl-layout__content">
      <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--1-col mdl-layout--medium-screen-only"></div>
        <div class="mdl-cell mdl-cell--10-col mdl-cell--8-col-tablet mdl-cell--4-col-phone">
          <%= yield %>
        </div>
    </div>
    </main>
  </body>
</html>

app/views/welcome/about.html.erb
<div class="welcome">
	<h2>Isso é realmente necessário?</h2>
	<p>Parece uma informação totalmente inutil, mas tudo bem...</p>

	<ul class="about">
		<li><b>Github: </b><a href="https://github.com/lleonardoll" target="_blank">lleonardoll</a></li>
		<li><b>Bitbucket: </b><a href="https://bitbucket.org/lleonardoll/" target="_blank">lleonardoll</a></li>
		<li><b>Facebook: </b><a href="https://www.facebook.com/llleonardolll" target="_blank">Leonardo Camp</a></li>
		<li><b>E-mail: </b>leofrederiche@gmail.com</li>
	</ul>
</div>

app/views/welcome/coming.html.erb
<center>
	<h1 style="color: #fff;">Em breve...</h1>
</center>

app/views/welcome/index.html.erb
<div class="welcome">
	<h2>Comente a inutilidade</h2>
	<p>Já imaginou poder postar algo totalmente inútil? como quando você está indo pra academia, quando está com fome, ou quando está com o namorado sem que ninguém te ignore?</p>

	<%= link_to "Comentar", comments_path, class: "mdl-button mdl-button--raised mdl-button--primary btn btn-welcome" %>
</div>